# Generated by Django 2.2.5 on 2022-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('regdate', models.DateField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('energy', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('sugars', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('calcium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('sodium', models.FloatField()),
                ('iron', models.FloatField()),
                ('zinc', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('transfat', models.FloatField()),
            ],
        ),
    ]
