# Generated by Django 2.2.5 on 2022-05-08 02:15

from django.db import migrations, models
import meal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portions', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to=meal.models.user_directory_path)),
                ('regdate', models.DateField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=30)),
                ('quantity', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('carbohydrate', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('phosphorus', models.FloatField(null=True)),
                ('sodium', models.FloatField(null=True)),
                ('potassium', models.FloatField(null=True)),
                ('magnesium', models.FloatField(null=True)),
                ('iron', models.FloatField(null=True)),
                ('zinc', models.FloatField(null=True)),
                ('cholesterol', models.FloatField(null=True)),
                ('transfat', models.FloatField(null=True)),
            ],
        ),
    ]
