# Generated by Django 2.2.5 on 2022-04-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Kid'),
        ),
        migrations.AddField(
            model_name='diet',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Meal'),
        ),
        migrations.AddField(
            model_name='diet',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meal.Nutrition'),
        ),
    ]
