# Generated by Django 4.0.1 on 2022-04-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.kid'),
        ),
        migrations.AddField(
            model_name='diet',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal'),
        ),
        migrations.AddField(
            model_name='diet',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meal.nutrition'),
        ),
    ]
