# Generated by Django 2.2.5 on 2022-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_regdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_regdate',
            field=models.DateTimeField(),
        ),
    ]
