# Generated by Django 2.2.5 on 2022-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20220418_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_moddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
