# Generated by Django 2.2.5 on 2022-04-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filename',
        ),
    ]
