# Generated by Django 2.2.5 on 2022-04-20 07:35

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220419_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to=board.models.board_directory_path),
        ),
    ]
