# Generated by Django 2.2.5 on 2022-04-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment_comment_moddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_moddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
