# Generated by Django 2.2.5 on 2022-04-20 12:51

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20220420_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.board_directory_path),
        ),
    ]
