# Generated by Django 2.2.5 on 2022-04-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_post_moddate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('board_name',)},
        ),
    ]
